@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.copper_additions.datagen.model;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;