@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.copper_additions.blocks.weatheringBlocks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;