@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.copper_additions.blockEntities;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;