@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.copper_additions.datagen.lootTables.modifier;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;